<?php include('header.php'); ?>
<h1>Update Customer</h1>
</div>
<div class="col-md-6 center-block">
    <form class="pure-form" method="post" action="/article/update/<?= $article['id'] ?>">
        <div class="form-group">
            <label for="name">Name</label>
            <input name="name" id="name" type="text" class="form-control" required value="<?= $article['name'] ?>"/>
        </div>

        <div class="form-group">
            <label for="body">Body</label>
            <textarea name="body" id="body" rows="10" class="form-control" required><?= $article['body'] ?></textarea>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-lg btn-success">Update</button>
        </div>
    </form>

</div>

<?php include('footer.php'); ?>
