<?php include('header.php'); ?>
    <h1>Article Detail</h1>
    </div>
    <div class="col-md-12 center-block">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Article Detail</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-4">
                    <p><strong>Name:</strong> <?= $article['name'] ?></p>
                </div>

                <div class="col-md-8">
                    <p><strong>Body:</strong> <?= $article['body'] ?></p>
                </div>

                <div class="col-md-4">
                    <a href="<?= $router->pathFor('article-edit', ['id' => $article['id']]) ?>">
                        <button type="button" class="btn btn-sm btn-info">edit</button>
                    </a>
                </div>

                <div class="col-md-4">
                    <a href="<?= $router->pathFor('article-delete', ['id' => $article['id']]) ?>">
                        <button type="button" class="btn btn-sm btn-danger">delete</button>
                    </a>
                </div>
            </div>

        </div>
    </div>

<?php include('footer.php'); ?>
