<?php include('header.php'); ?>
    <h1>New Article</h1>
    </div>
    <div class="col-md-6 center-block">
        <form class="pure-form" method="post" action="/article/new">
            <div class="form-group">
                <label for="name">Name</label>
                <input name="name" id="name" type="text" class="form-control" required/>
            </div>

            <div class="form-group">
                <label for="body">Body</label>
                <textarea name="body" id="body" rows="10" class="form-control" required></textarea>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success">Create</button>
            </div>
        </form>
    </div>

<?php include('footer.php'); ?>
