<?php include('header.php'); ?>
    <h1>All Articles</h1>
    </div>

<?php
if ($data['articles'] && is_array($data['articles'])):
    ?>
    <div class="panel panel-default">
        <div class="panel-heading">Viewing all articles</div>
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Actions</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($data['articles'] as $item): ?>
                <tr>
                    <td><?= $item['name'] ?></td>
                    <td>
                        <a href="<?= $router->pathFor('article-detail', ['id' => $item['id']]) ?>">
                            <button type="button" class="btn btn-xs btn-success">view</button>
                        </a>
                        <a href="<?= $router->pathFor('article-edit', ['id' => $item['id']]) ?>">
                            <button type="button" class="btn btn-xs btn-info">edit</button>
                        </a>
                        <a href="<?= $router->pathFor('article-delete', ['id' => $item['id']]) ?>">
                            <button type="button" class="btn btn-xs btn-danger">delete</button>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="alert alert-danger" role="alert">No current articles</div>
<?php endif; ?>
<?php include('footer.php'); ?>
